### ISSUE TITLE
Wrong offsetGet?

### ISSUE THREAD

**Issue by franz-josef-kaiser** [Toobo/PipePie#1]
_Note: I'm just looking through the code, so it could be that I understood something wrong here._

At the `DTO` class, there's the `(array) storage` property that seems to be used as internal storage for custom(?) data. When I look [at `offsetGet( $offset )`](https://github.com/Toobo/PipePie/blob/master/src/DTO.php#L97), then it seems that you are checking the object itself instead of the `storage` property for the value

```
return $this->offsetExists( $offset ) ? $this->storage[ $offset ] : null;
```

while `offsetSet( $offset, $val )` actually pushes into the `storage` array:

```
$this->storage[ $offset ] = $value;
```

**Comment by gmazzap** [comment]
The line:

``` php
$this->offsetExists($offset);
```

is equal to: 

``` php
array_key_exists($offset, $this->storage);
```

[Source](https://github.com/Toobo/PipePie/blob/master/src/DTO.php#L90-L93).

So it checks if the _key_ `$offset` is present in the array `$this->storage`.

It means that

``` php
public function offsetGet($offset)
{
    return $this->offsetExists($offset) ? $this->storage[$offset] : null;
}
```

is equal to:

``` php
public function offsetGet($offset)
{
    if (array_key_exists($offset, $this->storage)) {
         return $this->storage[$offset];
    } else {
        return null;
    }
}
```

So, data is saved by `offsetSet()` in the `$this->storage` array and is retrieved by `offsetGet()` from same array only if it is available.
